const UI_TEXT = {
  vi: {
    meta:{title:'Eco2go Vietnam — Vật liệu tự nhiên, cuộc sống tốt đẹp hơn',description:'Sản phẩm tự nhiên từ gáo dừa, xơ dừa và tre cho không gian sống xanh.'},
    nav:{home:'Trang chủ',products:'Danh mục',story:'Câu chuyện',contact:'Liên hệ',catalog:'Nhận catalogue',language:'Ngôn ngữ',admin:'Quản trị'},
    footer:{contact:'Liên hệ',catalog:'Danh mục',tableware:'Tableware từ gáo dừa',growing:'Growing media từ xơ dừa',landscape:'Giải pháp cảnh quan',origin:'Sản xuất tại Việt Nam · Xuất khẩu toàn cầu'},
    common:{view:'Thông tin sản phẩm',from:'Giá từ',quote:'Yêu cầu báo giá',call:'Gọi tư vấn',back:'Quay lại danh mục',all:'Xem toàn bộ',save:'Lưu sản phẩm',cancel:'Hủy',edit:'Sửa',remove:'Xóa',logout:'Đăng xuất',login:'Đăng nhập',reset:'Khôi phục dữ liệu gốc',search:'Tìm kiếm',samplePrice:'Giá minh họa'},
    home:{heroText:'Biến những phụ phẩm của cây dừa Việt Nam thành sản phẩm hữu ích, đẹp và bền vững cho bàn ăn, khu vườn và các dự án cảnh quan toàn cầu.',explore:'Khám phá {count} sản phẩm',years:'Năm xuất khẩu',lines:'Dòng sản phẩm',natural:'Chất liệu tự nhiên',storyTitle:'Không chỉ là sản phẩm xanh. Đó là một vòng đời mới cho vật liệu tự nhiên.',story1:'Thành lập năm 2017, Eco2go Vietnam phát triển và xuất khẩu các sản phẩm từ gáo dừa, xơ dừa và tre. Mỗi sản phẩm tận dụng nguồn vật liệu bản địa, giảm phụ thuộc vào nhựa và tạo ra giá trị sử dụng lâu dài.',story2:'Từ chén gáo dừa thủ công đến giá thể trồng cây và lưới chống xói mòn, danh mục 2026 phục vụ cửa hàng, nhà hàng, vườn ươm, nông nghiệp và dự án cảnh quan.',storyCta:'Xem danh mục 2026',whyTitle:'Thiết kế bởi thiên nhiên. Sẵn sàng cho kinh doanh.',principles:[['Vật liệu bền vững','Tận dụng gáo dừa, xơ dừa và tre — nguồn nguyên liệu tái tạo tại Việt Nam.'],['Danh mục đa dạng','Giải pháp cho tableware, làm vườn, nông nghiệp và cảnh quan.'],['Tùy chỉnh linh hoạt','Kích thước, màu sắc, đóng gói và khắc logo theo yêu cầu đơn hàng.'],['Kinh nghiệm xuất khẩu','Quy cách rõ ràng và hỗ trợ trực tiếp cho khách hàng quốc tế.']],collectionTitle:'Một trái dừa. Vô vàn khả năng.',collectionText:'Ba nhóm giải pháp thương mại từ danh mục Eco2go Vietnam.',categories:[['Tableware','Chén và ly gáo dừa thủ công cho F&B, retail và quà tặng.'],['Grow & Garden','Viên nén, giá thể, chậu và phụ kiện xơ dừa cho cây trồng.'],['Landscape','Lưới, thảm phủ, lưới che và cọc tre cho dự án ngoài trời.']],catalogNote:'{count} sản phẩm trong catalogue 2026',customNote:'Thông số và quy cách có thể tùy chỉnh theo đơn hàng.',contactTitle:'Đưa vật liệu tự nhiên ra thị trường.',contactText:'Liên hệ để nhận báo giá, tư vấn quy cách, mẫu sản phẩm hoặc catalogue chi tiết.'},
    products:{eyebrow:'Danh mục sản phẩm 2026',title:'{count} cách hợp tác cùng thiên nhiên.',intro:'Danh mục sản phẩm từ gáo dừa, xơ dừa và tre — dành cho bán lẻ, F&B, làm vườn, nông nghiệp và cảnh quan.',placeholder:'Tìm chén, chậu, giá thể, lưới...',empty:'Không tìm thấy sản phẩm phù hợp.',product:'Sản phẩm'},
    admin:{title:'Quản trị sản phẩm',loginTitle:'Đăng nhập quản trị',loginText:'Khu vực demo dành riêng cho tài khoản quản trị.',username:'Tài khoản',password:'Mật khẩu',invalid:'Thông tin đăng nhập không đúng.',demoWarning:'Demo frontend: cơ chế này không an toàn cho website production.',newProduct:'Tạo sản phẩm',productList:'Danh sách sản phẩm',nameVi:'Tên tiếng Việt',nameEn:'Tên tiếng Anh',taglineVi:'Tagline tiếng Việt',taglineEn:'Tagline tiếng Anh',shortVi:'Mô tả ngắn tiếng Việt',shortEn:'Mô tả ngắn tiếng Anh',descVi:'Mô tả chi tiết tiếng Việt',descEn:'Mô tả chi tiết tiếng Anh',advantagesVi:'Ưu điểm tiếng Việt (mỗi dòng một mục)',advantagesEn:'Ưu điểm tiếng Anh (mỗi dòng một mục)',specsVi:'Thông số tiếng Việt (Nhãn | Giá trị)',specsEn:'Thông số tiếng Anh (Label | Value)',slug:'Slug',image:'Đường dẫn ảnh',price:'Giá khởi điểm USD',category:'Nhóm sản phẩm',featured:'Sản phẩm nổi bật',sort:'Thứ tự',required:'Vui lòng điền đủ các trường bắt buộc và giá hợp lệ.',duplicate:'Slug đã tồn tại.',saved:'Đã lưu sản phẩm.',deleted:'Đã xóa sản phẩm.',confirmDelete:'Bạn chắc chắn muốn xóa sản phẩm này?',confirmReset:'Khôi phục toàn bộ dữ liệu catalogue gốc?',resetDone:'Đã khôi phục dữ liệu gốc.'},
    errors:{unauthorizedTitle:'Không có quyền truy cập',unauthorizedText:'Bạn cần đăng nhập bằng tài khoản quản trị để mở khu vực CRUD.',notFoundTitle:'Không tìm thấy trang',notFoundText:'Đường dẫn bạn yêu cầu không tồn tại.',home:'Về trang chủ',goLogin:'Đến trang đăng nhập'}
  },
  en: {
    meta:{title:'Eco2go Vietnam — Natural materials, better living',description:'Natural coconut shell, coir and bamboo products for greener living.'},
    nav:{home:'Home',products:'Catalog',story:'Our story',contact:'Contact',catalog:'Get catalog',language:'Language',admin:'Admin'},
    footer:{contact:'Contact',catalog:'Catalog',tableware:'Coconut shell tableware',growing:'Coir growing media',landscape:'Landscape solutions',origin:'Made in Vietnam · Shipped worldwide'},
    common:{view:'Product details',from:'Starting at',quote:'Request a quote',call:'Call us',back:'Back to catalog',all:'View all',save:'Save product',cancel:'Cancel',edit:'Edit',remove:'Delete',logout:'Log out',login:'Log in',reset:'Reset catalog data',search:'Search',samplePrice:'Sample price'},
    home:{heroText:'We transform Vietnamese coconut by-products into useful, beautiful and sustainable products for dining, gardening and landscape projects worldwide.',explore:'Explore {count} products',years:'Years exporting',lines:'Product lines',natural:'Natural materials',storyTitle:'More than green products. A new life cycle for natural materials.',story1:'Established in 2017, Eco2go Vietnam develops and exports products made from coconut shell, coir and bamboo. Each item uses local materials, reduces reliance on plastic and creates lasting value.',story2:'From handcrafted coconut bowls to growing media and erosion-control nets, the 2026 catalog serves retailers, restaurants, nurseries, agriculture and landscape projects.',storyCta:'View the 2026 catalog',whyTitle:'Designed by nature. Ready for business.',principles:[['Sustainable materials','Reclaimed coconut shell, coir and bamboo — renewable resources from Vietnam.'],['Diverse portfolio','Solutions for tableware, gardening, agriculture and landscaping.'],['Flexible customization','Sizes, colors, packing and logo engraving tailored to each order.'],['Export experience','Clear specifications and direct support for international buyers.']],collectionTitle:'One coconut. Endless possibilities.',collectionText:'Three commercial solution groups from the Eco2go Vietnam catalog.',categories:[['Tableware','Handcrafted coconut bowls and cups for F&B, retail and gifting.'],['Grow & Garden','Coir pellets, substrates, pots and accessories for healthy plants.'],['Landscape','Nets, mulch mats, shade sails and bamboo stakes for outdoor projects.']],catalogNote:'{count} products in the 2026 catalog',customNote:'Specifications and dimensions can be customized for each order.',contactTitle:'Bring natural materials to market.',contactText:'Contact us for pricing, specification advice, product samples or a detailed catalog.'},
    products:{eyebrow:'Product catalog 2026',title:'{count} ways to work with nature.',intro:'Natural coconut shell, coir and bamboo products for retail, F&B, gardening, agriculture and landscaping.',placeholder:'Search bowls, pots, substrate, nets...',empty:'No matching products found.',product:'Product'},
    admin:{title:'Product administration',loginTitle:'Admin login',loginText:'Demo area reserved for the administrator account.',username:'Username',password:'Password',invalid:'Invalid username or password.',demoWarning:'Frontend demo: this mechanism is not secure for production.',newProduct:'Create product',productList:'Product list',nameVi:'Vietnamese name',nameEn:'English name',taglineVi:'Vietnamese tagline',taglineEn:'English tagline',shortVi:'Vietnamese short description',shortEn:'English short description',descVi:'Vietnamese full description',descEn:'English full description',advantagesVi:'Vietnamese advantages (one per line)',advantagesEn:'English advantages (one per line)',specsVi:'Vietnamese specs (Label | Value)',specsEn:'English specs (Label | Value)',slug:'Slug',image:'Image path',price:'Starting price USD',category:'Product category',featured:'Featured product',sort:'Sort order',required:'Complete all required fields and enter a valid price.',duplicate:'This slug already exists.',saved:'Product saved.',deleted:'Product deleted.',confirmDelete:'Are you sure you want to delete this product?',confirmReset:'Reset all products to the original catalog?',resetDone:'Original catalog restored.'},
    errors:{unauthorizedTitle:'Access denied',unauthorizedText:'Log in with the administrator account to access product CRUD.',notFoundTitle:'Page not found',notFoundText:'The requested route does not exist.',home:'Back to home',goLogin:'Go to login'}
  }
};

const PRODUCT_EN = {
  'coconut-shell-bowl':{tagline:'Natural coconut shell bowl',short:'Handcrafted bowls made from reclaimed coconut shells, each with a unique natural character.',desc:'Made from reclaimed coconut shells, these bowls are a reusable, sustainable alternative to conventional tableware. Each piece is handcrafted and naturally unique, ideal for smoothie bowls, salads, fruit, desserts and ice cream.',advantages:['100% natural and sustainable','Handcrafted from reclaimed coconut shells','Lightweight, durable and reusable','Food-safe and easy to clean','Unique natural shape and texture','Biodegradable and plastic-free','Custom logo engraving available'],specs:[['Size','Small: H5.5–6.5 x D8–10cm · Medium: H5.5–6.5 x D11–13cm · Jumbo: H7–8.5 x D10–13cm'],['Shape','Round with balanced bottom'],['Finish','Raw or polished'],['Logo','Laser engraving, custom on request'],['Ice cream version','100g / 150g / 200g / 250g / 300g — oval or natural shape']]},
  'coconut-shell-cup':{tagline:'Handcrafted coconut shell cup',short:'A distinctive tropical drink cup handcrafted from reclaimed coconut shell.',desc:'Coconut Shell Cups offer a stylish and sustainable way to serve cocktails, smoothies, juices and tropical drinks. Every cup is durable, reusable, biodegradable and naturally unique.',advantages:['100% natural reclaimed coconut shell','Handcrafted with unique shape and texture','Lightweight, durable and reusable','Food-safe and easy to clean','Biodegradable and zero-waste','Available with or without a base','Custom logo engraving available'],specs:[['Size','Customized to order'],['Finish','Raw or polished'],['Base','With or without base'],['Logo','Laser engraving, custom on request']]},
  'coir-pellet':{tagline:'Coir seed-starting pellet',short:'Compact coir pellets with excellent water retention for seeds and seedlings.',desc:'Compressed from natural coconut coir, these compact pellets expand with water into a loose, soil-like growing medium. Their moisture retention and aeration create an ideal environment for seed germination and healthy young roots.',advantages:['Optimal water retention','Good aeration','Biodegradable and eco-friendly','Renewable resource','Compact and convenient','pH neutral','Encourages strong root development','Low risk of diseases and weeds','Lightweight and easy to handle','Versatile for planting'],specs:[['Normal size','35mm x 18mm thick · 42mm x 8mm thick'],['Expanded size','38mm x 60mm thick · 43mm x 50mm thick'],['Packing','1,000 pieces per carton']]},
  'coco-peat-block':{tagline:'Compressed coir growing block',short:'Lightweight compressed coco peat with excellent moisture retention.',desc:'Coco Peat Blocks expand into a loose, soil-like texture when hydrated. This lightweight and sustainable substrate provides excellent water retention and aeration for seed starting, gardening and horticulture.',advantages:['Sustainable and renewable','Excellent water retention','Good aeration','Lightweight','pH neutral','Free from weeds and pathogens','Easy to rehydrate'],specs:[['2kg block','H5 x 30 x 30cm — expands to 23–24 liters'],['5kg block','H15 x 30 x 30cm — expands to 70–75 liters'],['EC','0.5'],['pH','5.5–6.5'],['Moisture','< 20%'],['Treatment','Washed'],['Packing','1–1.1 MTS per pallet'],['Loading','20 pallets per 40’HC container']]},
  'coco-husk-chips':{tagline:'Coconut husk chips for growing media',short:'Premium husk chips providing strong drainage and aeration for healthy roots.',desc:'Made from premium coconut husks, these chips balance water retention, aeration and drainage. They are ideal for orchids, nurseries, hydroponics and horticulture.',advantages:['100% natural and biodegradable','Low EC option < 0.5 mS/cm','High EC option > 2.5 mS/cm','Excellent water retention and drainage'],specs:[['Size','H15 x 30 x 30cm'],['Weight','4.5kg — expands to 70–80 liters'],['EC','0.5'],['pH','5.5–6.5'],['Moisture','< 20%'],['Treatment','Washed'],['Packing','1 MTS per pallet'],['Loading','20 pallets per 40’HC container']]},
  'coir-pot':{tagline:'Biodegradable coir nursery pot',short:'Natural coir pots that reduce transplant shock and support healthy roots.',desc:'Made from coconut coir, these biodegradable pots deliver excellent aeration and moisture retention. Plants can be placed directly into the soil without disturbing the root system.',advantages:['Faster plant growth','Encourages a strong root system','Rich in nutrients','pH neutral, odorless and lightweight','Free from weeds and diseases','Retains moisture without waterlogging','Eliminates transplant shock','Sustainable and biodegradable','Enhanced air porosity'],specs:[['Round pots','No.3031 6x4xH5.5cm · No.3032 8.5x5.5xH8cm · No.3033 11x7.5xH10cm · No.3071 5.5x3.5xH5cm · No.3072 10x6.5xH9cm · No.3134 13x10xH11.5cm'],['Square pots','No.3078 8.5x7xH5.5cm · No.3099 10x9xH6.2cm · No.3136 11x10xH7.7cm'],['Nursery trays','8-cell tray No.3097 · 10-cell tray No.3096']]},
  'coconut-shell-pot':{tagline:'Whole coconut shell planter',short:'Natural planters made from cleaned and dried whole coconut shells.',desc:'A visually distinctive, biodegradable planter made from cleaned and dried coconut shell. It offers a sustainable alternative to conventional pots and integrates naturally into the growing environment.',advantages:['Eco-friendly and sustainable','Biodegradable','Good drainage','Lightweight and easy to handle','Natural insulation','Promotes air circulation','Long-lasting','Versatile for planting'],specs:[['Size','H9–10cm / D9–11cm · H5–6cm / D7–9cm'],['Customization','Dimensions available on request']]},
  'coir-moss-pole':{tagline:'Coir support pole for climbing plants',short:'Moisture-retaining coir poles with a natural surface for climbing roots.',desc:'Coir Moss Poles provide natural support for vines and tropical houseplants. Their textured, moisture-retaining surface encourages roots to attach and climb while the coir eventually enriches the soil.',advantages:['Natural support for climbing plants','Improved air circulation','Biodegradable and eco-friendly','Sustainable material','Easy to install','Suitable for many climbing plants','Strong and stable structure','No harmful chemicals','Retains moisture'],specs:[['Length','50 / 60 / 80 / 90 / 100 / 110 / 120cm'],['Customization','Dimensions available on request']]},
  'coir-mulch-mat':{tagline:'Coir tree mulch mat',short:'Circular coir mats that retain moisture and suppress weeds around plants.',desc:'This circular biodegradable coir layer protects the base of trees and plants. It retains water, controls weeds, moderates temperature and supports healthier soil conditions.',advantages:['Sustainable material','Weed suppression','Moisture retention','Temperature regulation','Erosion control','Improved aeration','Enhanced soil structure','Resistant to rapid decay','Protects against lawn equipment damage'],specs:[['Diameter','20 / 25 / 30 / 40 / 50 / 60cm'],['Center hole','3–10cm'],['Customization','Dimensions available on request']]},
  'coir-fiber-liner-roll':{tagline:'Coir liner roll for planters',short:'Continuous natural coir lining for hanging baskets and planters.',desc:'Coir Fiber Liner Rolls provide a natural, biodegradable lining for baskets and planters. They retain moisture while allowing drainage and create favorable conditions for root development.',advantages:['Natural and sustainable material','Biodegradable','Excellent water retention','Good drainage','Supports root development','Suppresses weeds','Regulates temperature','Reduces soil erosion','Durable and long-lasting'],specs:[['Width','20 / 50 / 60 / 80 / 100 / 200cm'],['Length','10m or 20m'],['Thickness','3mm / 6mm / 10mm'],['Customization','Dimensions available on request']]},
  'coir-net':{tagline:'Coir erosion-control net',short:'Open-weave coir netting that stabilizes soil and supports vegetation.',desc:'Coir Net is a natural biodegradable mesh for soil stabilization and erosion control. It holds soil in place while allowing vegetation to establish, replacing synthetic erosion-control materials.',advantages:['Natural and biodegradable','Retains moisture','Regulates temperature','Protects seed and soil from stormwater runoff','Breaks down after 3–5 years','Protects seed from birds, animals and foot traffic','Flexible open-weave construction','Easy to install'],specs:[['Size','20m x 2m'],['Weave','Single-Single / Double-Single / Double-Double'],['Wire diameter','3.5–3.6mm'],['Yarn thickness','3–5mm'],['Weight','200 / 400 / 700 / 900 g/m²']]},
  'coir-shade-sail':{tagline:'Natural coir shade sail',short:'Breathable, sustainable shade made from 100% natural coconut fiber.',desc:'Coir Shade Sail provides effective sun protection while allowing air to circulate, reducing heat buildup outdoors. It is durable, biodegradable and ideal for gardens, patios, cafés, resorts, greenhouses and landscape projects.',advantages:['Natural eco-friendly shade solution','Durable and weather-resistant','Excellent airflow and ventilation','Biodegradable and sustainable','Suitable for gardens, patios, cafés and resorts'],specs:[['Size','2x3m / 3x3m / 3x4m / 4x4m / 4x6m / 5x5m / 5x6m / 8x8m / triangular sizes or custom'],['Shape','Rectangle, square or triangle'],['Loops','Steel or coir loops'],['Weight','650–700 gsm']]},
  'bamboo-stake':{tagline:'Bamboo plant support stake',short:'Slim, strong bamboo stakes that support upright plant growth.',desc:'Bamboo Stakes are lightweight yet sturdy supports for gardening and horticulture. They help plants grow upright and reduce bending or breakage while providing a natural, sustainable alternative.',advantages:['Sustainable material','Strong and durable','Easy to cut and shape','Resistant to pests and decay','Cost-effective','Lightweight','Easy to install','Reusable','Available in many sizes'],specs:[['Height','50–100 / 120 / 150 / 200 / 300cm'],['Diameter','D8–18mm'],['Customization','Custom size and color available']]}
};

function getText(locale, path, params={}){
  const dictionary=UI_TEXT[locale]||UI_TEXT.vi;
  let value=path.split('.').reduce((node,key)=>node?.[key],dictionary);
  if(typeof value!=='string') return value ?? path;
  return value.replace(/\{(\w+)\}/g,(_,key)=>params[key]??`{${key}}`);
}
